### ISSUE TITLE
ImportError: cannot import name 'BaseEnvironment' from partially initialized module 'rl

### ISSUE THREAD

**Issue by Tizzzzy** [ChicagoHAI/active-example-selection#1]
Hi, 
I followed every step in the README. I created python=3.9 conda environment. My torch version is Version: 2.3.1+cu118. I did `pip install .`. Then, when I run this command: `python src/rl/main.py rl_configs/random-agent.yaml`, I get the following error:

``` bash
Traceback (most recent call last):
  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/active-example-selection/src/rl/main.py", line 9, in <module>
    from rl import AGENTS, ENVIRONMENTS
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/active-example-selection/lib/python3.9/site-packages/rl/__init__.py", line 1, in <module>
    from rl.agents import DQNAgent, RandomAgent
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/active-example-selection/lib/python3.9/site-packages/rl/agents/__init__.py", line 1, in <module>
    from rl.agents.dqn_agent import DQNAgent
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/active-example-selection/lib/python3.9/site-packages/rl/agents/dqn_agent.py", line 15, in <module>
    from rl import BaseEnvironment
ImportError: cannot import name 'BaseEnvironment' from partially initialized module 'rl' (most likely due to a circular import) (/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/active-example-selection/lib/python3.9/site-packages/rl/__init__.py)
```

**Comment by y0mingzhang** [comment]
should be fixed with the latest commit

**Comment by Tizzzzy** [comment]
After I pull the latest version, the error still shows:
```bash
Traceback (most recent call last):
  File "/research/cbim/medical/lh599/research/ruijiang/Dong/demonstration_selection/active-example-selection/src/rl/main.py", line 9, in <module>
    from rl import AGENTS, ENVIRONMENTS
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/active-example-selection/lib/python3.9/site-packages/rl/__init__.py", line 1, in <module>
    from rl.agents import DQNAgent, RandomAgent
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/active-example-selection/lib/python3.9/site-packages/rl/agents/__init__.py", line 1, in <module>
    from rl.agents.dqn_agent import DQNAgent
  File "/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/active-example-selection/lib/python3.9/site-packages/rl/agents/dqn_agent.py", line 15, in <module>
    from rl import BaseEnvironment
ImportError: cannot import name 'BaseEnvironment' from partially initialized module 'rl' (most likely due to a circular import) (/research/cbim/medical/lh599/research/ruijiang/miniconda/envs/active-example-selection/lib/python3.9/site-packages/rl/__init__.py)
```
